title: Physics 50 <br> Module 1
logo: /images/phys-logo.png
description: Harvey Mudd College
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
relative_links:
  enabled:     true
  collections: false
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true